language: node_js

node_js:
- 8.0

before_script:
- npm install --dev

script:
- npm test
- npm run lint

notifications:
  email: false

deploy:
  provider: npm
  email: "EMAIL_ADDRESS"
  api_key: "NPM_AUTH_TOKEN"
  tag: next
  on:
    tags: true
    all_branches: true
